### ISSUE TITLE
Support file names for code blocks in markdown

### ISSUE THREAD

**Issue by Croccifixio** [Croccifixio/blog#11]
The markdown parser should be extended to support passing a file name as a part of the code block language. The file name is to be presented alongside the code block when the HTML is rendered.

The proposed syntax - in which the file name is wrapped in brackets - is shown below:

```css(assets/style.css)
body {
  display: grid;
}
```
